export const constant = {
    ACTIONS:{
        ADD:'ADD',
        DELETE:'DELETE',
        COMPLETE:'COMPLETE',
        SET_VISIBILITY:'SET_VISIBILITY',
        TOGGLE:'TOGGLE'
    },
    VISIBILITY:{
        SHOW_ALL:'SHOW_ALL',
        SHOW_COMPLETE:'SHOW_COMPLETE',
        SHOW_ACTIVE:'SHOW_ACTIVE'
    },
    VISIBILITYNAME:{
        SHOW_ALL:'ALL',
        SHOW_COMPLETE:'COMPLETE',
        SHOW_ACTIVE:'ACTIVE'
    },
    REQUEST:{
        REQUEST_POSTS:"REQUEST_POSTS",
        RECEIVE_POSTS:'RECEIVE_POSTS'
    }
}
